### ISSUE TITLE
Support different modelId DataTypes

### ISSUE THREAD

**Issue by duncanhoggan** [blankstar85/sequelize-central-log#21]
Currently the `modelId` assumes a PK datatype of `INTEGER`.
Please can we open this up so we can configure the type of the `modelId`, for example a common pk type is UUID or STRING.

Would be a very minor config change and would provide a lot of value.
I'm happy to prepare a PR for this if you want to include this.

Thanks for the incredible library btw

**Comment by blankstar85** [comment]
I don't know why i didn't see this sooner, Sorry for the late reply. Thank you for the comments!! I was looking at the primary keys and looking to see the way to make it more dynamic. All my primary keys are INT(10). Although that def seems to be an old way of doing things. I'll see if i can't get this updated asap for you.
